name: Compiling

on:
  push:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.1.7
      - name: Set up JDK
        uses: actions/setup-java@v4.3.0
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Build artifacts
        run: ./gradlew build
      - name: Upload assets to GitHub
        uses: softprops/action-gh-release@v2.0.8
        with:
          files:  build/libs/*
          draft: true
          fail_on_unmatched_files: true
