name: Compiling

on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.1.7
      - name: Set up JDK
        uses: actions/setup-java@v4.3.0
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Permission up
        run: git update-index --chmod=+x build.cmd
      - name: Build artifacts
        run: ./gradlew build -Pbuild.release=true
      - name: Upload assets to GitHub
        uses: AButler/upload-release-assets@v3.0
        with:
          # Filter built files to disregard -sources and -dev, and leave only the minecraft-compatible jars.
          files: 'build/libs/*[0-9].jar;LICENSE'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
